title: Perlas Arnold
email: hello@perlasarnold.me
description: Insights, notes, and experiments from Perlas Arnold.
url: "https://perlasarnold.me"
baseurl: ""
timezone: America/Los_Angeles
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
author:
  name: Perlas Arnold
nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Family
    url: "https://docs.google.com/spreadsheets/d/1gcWSrqBbkT3ygMAU_9x00z6gBy7V5585r0pIs4cZJYQ/edit?usp=sharing"
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
